services:
  redis:
    image: redis:7
    container_name: online-store-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - easymlops_network

  postgres:
    image: postgres:15
    container_name: offline-store-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_DB=feast_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./my_feature_repo/postgres-feast/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - easymlops_network

volumes:
  redis_data:
  postgres_data:

# networks:
#   easymlops_network:
#     external: true
networks:
  easymlops_network:
    name: easymlops_network
