services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    # depends_on:
    #   - redis
    networks:
      - easymlops_network 
    env_file:
      - .env 
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      FEATURE_REPO_PATH: "/app/my_feature_repo/feature_repo"
      REDIS_URL: "redis://redis:6379"
      MONGO_DB_URL: ${MONGO_DB_URL}
      MLFLOW_TRACKING_URI: "http://3.80.110.50:5000"
      OTLP_ENDPOINT: "http://otel-collector:4317"

  streamlit:
    build:
      context: .
      dockerfile: streamlit/Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    networks:
      - easymlops_network

networks:
  monitoring:
    driver: bridge # This creates the network
# networks:
#   easymlops_network:
#     name: easymlops_network