services:
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    # depends_on:
    #   - fastapi
    networks:
      - easymlops_network

  grafana:
    image: grafana/grafana:10.1.5 
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - easymlops_network

  ### OPENTELEMETRY COLLECTOR ###
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.98.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./observability/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "9464:9464"  # Prometheus exporter
    networks:
      - easymlops_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    container_name: logstash
    volumes:
      - ./observability/logstash:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    networks:
      - easymlops_network

  ### FILEBEAT ###
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.0
    volumes:
      - ./observability/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - logstash
    networks:
      - easymlops_network

  ### ELASTICSEARCH ###
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - xpack.security.enabled=true
      # - ELASTIC_PASSWORD=admin
    ports:
      - "9200:9200"
    networks:
      - easymlops_network

  ### KIBANA ###
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # - ELASTICSEARCH_USERNAME=elastic  # Default username
      # - ELASTICSEARCH_PASSWORD=admin  
    # volumes:
    #   - ./observability/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    networks:
      - easymlops_network

  ### SLACK ALERTING (ALERTMANAGER) ###
  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: alertmanager
    volumes:
      - ./observability/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - easymlops_network

volumes:
  grafana_data:

# networks:
#   monitoring:
#     name: monitoring
#   # This connects to the pre-existing network
# networks:
#   easymlops_network:
#     external: true
networks:
  easymlops_network:
    name: easymlops_network