version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - monitoring  # Ensure it's on the same network as Prometheus
    environment:
      FEATURE_REPO_PATH: "/app/my_feature_repo/feature_repo"
      PREPROCESSOR_PATH: "/app/final_model/preprocessor.pkl"
      REDIS_URL: "redis://redis:6379"
      MONGO_DB_URL: "mongodb+srv://neerajjj6785:Admin123@cluster0.maegd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      MLFLOW_TRACKING_URI: "http://ec2-54-242-223-94.compute-1.amazonaws.com:5000/"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    networks:
      - monitoring

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - monitoring

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=neeraj
      - POSTGRES_DB=feast_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring

volumes:
  redis_data:
  postgres_data:

networks:
  monitoring:
    driver: bridge # This creates the network
