amt:
  drift_detected: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - b1
    - false
    - true
    state: !!python/tuple
    - 3
    - '|'
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AQ==
  p_value: 0.03349578783122764
cc_num:
  drift_detected: &id002 !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AA==
  p_value: 0.6934198469413929
city_pop:
  drift_detected: *id002
  p_value: 0.8657231217897363
is_fraud:
  drift_detected: *id002
  p_value: 1.0
trans_month:
  drift_detected: *id002
  p_value: 0.28395496237445417
trans_year:
  drift_detected: *id002
  p_value: 1.0
transaction_id:
  drift_detected: *id002
  p_value: 0.40574658931120455
