columns:
  - transaction_id: int64
  - event_timestamp: datetime64[ns]
  - cc_num: int64
  - amt: float64 
  - merchant: string       
  - category: string 
  - gender: string             
  - job: string                   
  - trans_year: int64
  - trans_month: int64     
  - is_fraud: int64        
  - city_pop: int64           
             

numeric_columns:
  - cc_num
  - amt
  - city_pop
  - is_fraud
  - trans_year
  - trans_month
  - is_fraud
  - transaction_id

categorical_columns:
  - merchant
  - category
  - gender
  - job
