global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["fastapi:8000"] 
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464'] 
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']